### ISSUE TITLE
Cannot install 'codeintel' through pip

### ISSUE THREAD

**Issue by kgizdov** [SublimeCodeIntel/SublimeCodeIntel#496] opened 2015-03-26 21:16 UTC
Hi,

The latest version of SublimeCodeIntel requires the installation of `codeintel` through `pip`. However, on my Ubuntu 14.04.2 LTS it will not install. I have tried all the possible variants I can think of. I have tried with pip, pip2, directly through pipelining pip into python, python3, python3.4 and all of the combinations with and without 'sudo' (yes, I know it's a for python 2, but I am desperate). I have double and triple checked the install instructions at pip.pypa.io and have done troubleshooting on my pip installation. I am unable to find the issue that prevents the installation.

As I understand, `codeintel` is being locally built and installed, but I think the build completely fails. Downloading it works fine and I have checked that pip acquires the correct version. However, when the build starts (regardless of the method involved) it spits out many compiler warnings such as `cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]`. Then it finally fails with the following error:

```
scintilla/lexers/LexUDL.cxx:22:18: fatal error: pcre.h: No such file or directory

 #include <pcre.h>

                  ^

compilation terminated.

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-qMd4bj/codeintel/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-bq6N5V-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-qMd4bj/codeintel
```

I have checked and `#include <pcre.h>` works normally, but I cannot confirm if it is included properly in the temp build folder that `codeintel` runs.

Any suggestions or troubleshooting tips are much appreciated. I hope this helps and the issue can be resolved quickly as I do rely heavily on SublimeCodeIntel.

Thanks.

**Comment by Kronuz** [comment] 2015-03-26 22:52
No, the latest version still doesn't require the CodeIntel python package, that will be until next major version (v3.0.0), we are just making sure everyone gets prepared.

That said, what you need is to install `libpcre-dev` (using apt-get) for the build error you mentioned above.

**Comment by kgizdov** [comment] 2015-03-26 23:10
Sorry, I read the notice wrong.

I installed `libpcre-dev` and it only kinda worked with `sudo pip2 install codeintel`. However, the amount of compiler warnings/errors is over 9000. Seriously, I am not sure what is causing it, but it is definitely not ok. `pip` claims the package is installed, but I cannot be sure if it compiled correctly. Here's the complete output from the terminal on [pastebin](http://pastebin.com/uUHuwvUP).

**Comment by Kronuz** [comment] 2015-03-27 05:43
Those seem to only be warnings of a bug in the setup, I believe you can safely ignore those. You seem to have a working `codeintel` installed. Shall you run the command codeintel, you should be able to see two lines logged with the status and a 2{} on the console (ctrl+c to exit from the command)

You'd need SublimeCodeIntel 3 to use that `codeintel` command. SublimeCodeIntel is a package control prerelease, so you'd have to enable prereleases for SublimeCodeIntel in the package control settings to install it.

**Comment by srus** [comment] 2015-03-27 10:23
I got this on Ubuntu 12.04.5:

```bash
    /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.6/libstdc++.a(functexcept.o): relocation R_X86_64_32 against `std::bad_exception::~bad_exception()' can not be used when making a shared object; recompile with -fPIC
    
    /usr/lib/gcc/x86_64-linux-gnu/4.6/libstdc++.a: could not read symbols: Bad value
    
    collect2: ld devolvió el estado de salida 1
    
    error: command 'g++' failed with exit status 1
    
    ----------------------------------------
    Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-sT5Umj/CodeIntel/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-VsF5R0-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-sT5Umj/CodeIntel
```
Do I need some library maybe?

**Comment by Kronuz** [comment] 2015-03-27 14:57
Can you please try installing `libstdc++-static` and trying again? It seems your static libstdc++ library was not installed with support for linking against shared libraries.

We need wheels built for every platform we can, having Linux wheels would help. If anyone can manage to build the CodeIntel package, would you mind re-building as a wheel? You'll need the https://pypi.python.org/packages/source/C/CodeIntel/CodeIntel-0.1.6.tar.gz file in PyPI, the wheel package (`pip install wheel`). Untar the file and run `python setup.py bdist_wheel` then share with me the `dist/*.whl` file. We'll need someone who can do this process for every release, on every platform, if you are interested in collaborating.

**Comment by srus** [comment] 2015-03-27 18:15
[It seems that](https://github.com/xerial/snappy-java#building-linux-x86_64-binary) in most 64-bit Linux distributions, g++ is not enabled to static linking libstdc++, so I'm following that snippet to try to compile a new version of gcc (I picked 4.8.4) with the required flags. I'm brand new building packages, but if I succeed (it's been compiling for more than 1 hour and hasn't stopped yet), I'll try to build the wheel.

**Comment by srus** [comment] 2015-03-28 13:09
Ok It's done! https://dl.dropboxusercontent.com/u/1268842/CodeIntel/CodeIntel-0.1.6-cp27-none-linux_x86_64.whl

**Comment by kylebradshaw** [comment] 2015-03-29 01:05
I got a similar error on OSX 10.10.2

```
    cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -arch i386 -pipe -Iscintilla/src -Iscintilla/lexlib -Iscintilla/lexers -Iscintilla/include -Isilvercity/PySilverCity/Src -Isilvercity/Lib/Src -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c scintilla/lexers/LexUDL.cxx -o build/temp.macosx-10.10-intel-2.7/scintilla/lexers/LexUDL.o

    scintilla/lexers/LexUDL.cxx:22:10: fatal error: 'pcre.h' file not found

    #include <pcre.h>

             ^

    1 error generated.

    error: command 'cc' failed with exit status 1

    ----------------------------------------
    Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-Y5o_92/codeintel/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-8oKz1j-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-Y5o_92/codeintel
```

I saw a couple of pcre packages that are installable via homebrew. Any guidance?

**Comment by Kronuz** [comment] 2015-03-29 05:00
`brew inatall pcre`

**Comment by ghreat** [comment] 2015-03-30 16:00
OS X Yosemite 10.10.2
```bash
> brew info pcre
pcre: stable 8.36 (bottled)
http://www.pcre.org/
/usr/local/Cellar/pcre/8.36 (146 files, 5,9M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/pcre.rb
==> Options
--universal
	Build a universal binary
```
```bash
> python -V
Python 2.7.6
```
```bash
> pip -V
pip 6.0.8 from /Library/Python/2.7/site-packages/pip-6.0.8-py2.7.egg (python 2.7)
```
```bash
> cc -v
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.1.0
Thread model: posix
```
```bash
> sudo -H pip install -U codeintel

... many pages of compiler messages and warnings ...

scintilla/lexers/LexUDL.cxx:22:10: fatal error: 'pcre.h' file not found

#include <pcre.h>

         ^

1 error generated.

error: command 'cc' failed with exit status 1

----------------------------------------
Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-wIlxki/codeintel/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-GUXBBc-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-wIlxki/codeintel
```

**Comment by syerad** [comment] 2015-04-01 08:08
I'm still facing this compilation error when I try to install codeintel via pip:
<code>
compilation terminated.
    
 error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
 ----------------------------------------
    Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-tFt0ro/subprocess32/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-vjR6Gn-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-tFt0ro/subprocess32

</code>

Any suggestions?

**Comment by initialize** [comment] 2015-04-01 08:12
```
> sudo pip install -U codeintel

(...)

creating build/temp.linux-x86_64-2.7/scintilla/lexers

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Iscintilla/src -Iscintilla/lexlib -Iscintilla/lexers -Iscintilla/include -Isilvercity/PySilverCity/Src -Isilvercity/Lib/Src -I/usr/include/python2.7 -c silvercity/PySilverCity/Src/PyLexerModule.cxx -o build/temp.linux-x86_64-2.7/silvercity/PySilverCity/Src/PyLexerModule.o

cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]

In file included from silvercity/PySilverCity/Src/PyLexerModule.cxx:5:0:

silvercity/PySilverCity/Src/PyLexerModule.h:8:20: fatal error: Python.h: Filen eller katalogen finns inte

 #include <Python.h>

                    ^

compilation terminated.

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_mikael/codeintel/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-hDrYji-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_mikael/codeintel
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.4', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 185, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 42: ordinal not in range(128)
```

"Filen eller katalogen finns inte" = "File or directory not found".

**Comment by peterorum** [comment] 2015-04-03 12:32
On Yosemite, after `brew install pcre`, still ...

#include <pcre.h>

         ^

1 error generated.

error: command 'cc' failed with exit status 1

**Comment by Kronuz** [comment] 2015-04-03 13:40
You need:
```
export CFLAGS="-I/usr/local/include -g -O2"
export CXXFLAGS="-I/usr/local/include -g -O2"
export LDFLAGS="-L/usr/local/lib"
```

**Comment by peterorum** [comment] 2015-04-03 13:45
I got this working eventually. I don't have an exact script, but these helped...
export CPATH="/usr/local/bin"
upgraded pip with sudo easy_install --upgrade pip
temporarily sudo chmod 777 site-packages

then ... 
pip install -U codeintel

Ended up with /usr/local/bin/codeintel which runs.

**Comment by Kronuz** [comment] 2015-04-03 14:05
Well, congratulations, you can now upgrade to and use SublimeCodeIntel 3.0 alpha.

Having accepted than this is yet an alpha release, and if you are willing and ready to try it out, follow the next steps to upgrade:

1. **Make sure you have properly installed CodeIntel package before proceeding, it's a requirement**

2. In Sublime Text, go to `Preferences > Package Settings > Package Control > Settings - User` and add SublimeCodeIntel to the list of prereleases `install_prereleases": ["SublimeCodeIntel"],`.

3. Run the *Package Control: Upgrade Package* command from the command palette and select `SublimeCodeIntel` (note it should say there it's v3.0).

4. Restart Sublime Text when it's done upgrading.

**Comment by peterorum** [comment] 2015-04-04 01:24
Thanks - alpha installed ok and so far so good in javascript.

**Comment by Kronuz** [comment] 2015-04-16 16:33
Please try installing v0.1.7 (which fixed the `pcre.h` issue and other things): `pip install -U codeintel`

**Comment by syerad** [comment] 2015-04-23 20:26
v0.1.7 is working. Thanks!

**Comment by AsmaFaraji** [comment] 2016-09-02 12:36
hi I face the below error while installing a pillow 
Command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip_build_asma/pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-iysfjtik-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_asma/pillow
Storing debug log for failure in /home/asma/.pip/pip.log

**Comment by deresh** [comment] 2016-09-29 08:09
@Kronuz 

There seems to be a problem with codeintel build. As linux has case sensitive filesystem, build fails for silvercity as folder is names "SilverCity" and build expects "silvercity".

After this is fixed it compiles ok on Ubuntu 16.04

**Comment by adnedelcu** [comment] 2016-10-21 14:05
I got to fix the issue with the SilverCity by downloading the **codeintel source archive** and making a duplicate of the **SilverCity** folder named **silvercity**.

After that, I just ran from the codeintel source extracted folder:
```
python setup.py build
python setup.py install
```

**Comment by Kronuz** [comment] 2017-05-21 01:02
The silvercity issue should be fixed in CodeIntel 0.10.1 and it also upgrades Komodo's codebase. `pip install -U codeintel`

**Closed by Kronuz** 2017-05-21 01:02 UTC

**Comment by borela** [comment] 2017-05-24 23:06
@Kronuz Is it possible to support python 3?

```
Collecting codeintel
  Using cached CodeIntel-0.10.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ALEXAN~1\AppData\Local\Temp\pip-build-14y8ghtk\codeintel\setup.py", line 7, in <module>
        import codeintel
      File "C:\Users\ALEXAN~1\AppData\Local\Temp\pip-build-14y8ghtk\codeintel\codeintel\__init__.py", line 204
        resource.setrlimit(resource.RLIMIT_AS, (2 * GB, -1L))
                                                          ^
    SyntaxError: invalid syntax
```

**Comment by Kronuz** [comment] 2017-05-25 03:38
@borela, I'm working at it! ...donations always welcome ;)
