### ISSUE TITLE
CPU 100%, stuck at "Updating indexes... " when editing a PHP file.

### ISSUE THREAD

**Issue by heleifz** [SublimeCodeIntel/SublimeCodeIntel#286] opened 2013-07-31 13:47 UTC
## Log file
Starting logging SublimeCodeIntel v2.0.1 rev GIT-314f1b8a (1375275577) on Wed Jul 31 21:36:18 2013

+ Debug: Invalid language: Plain text. Available: JavaScript, Mason, XBL, XUL, RHTML, SCSS, Python, HTML, Ruby, Python3, XML, Sass, XSLT, Django, HTML5, Perl, CSS, PHP, Less, Smarty, Node.js, Tcl, TemplateToolkit, Twig
+ Debug: Invalid language: Plain text. Available: JavaScript, Mason, XBL, XUL, RHTML, SCSS, Python, HTML, Ruby, Python3, XML, Sass, XSLT, Django, HTML5, Perl, CSS, PHP, Less, Smarty, Node.js, Tcl, TemplateToolkit, Twig
+ Info: processing `PHP': please wait...
Updating indexes for 'PHP'... The first time this can take a while.
scan_purelang: path: u'/home/helei/1.php' lang: PHP
scan_multilang: path: u'/home/helei/1.php' lang: PHP
+ Info: Updating indexes for 'PHP'... The first time this can take a while.
+ Info: Updating indexes... The first time this can take a while. Do not despair!
+ Info: Updating indexes... The first time this can take a while. Do not despair!

**Comment by xabikip** [comment] 2015-01-20 23:06
I have the same problem when I go to save PHP files.
Ubuntu 12.04, (x64), Sublime Text 2.0.2 Build 2221.

**Comment by cvetan** [comment] 2015-01-22 06:22
Even the latest updates, didn't fixed this. ST2 Ubuntu 12.04 x64. There were several updates, for the past few days, but still this remains.

**Comment by Kronuz** [comment] 2015-01-22 14:43
The current state of this thread of comments is of no use because the reasons for every comment could be too many to tackle as a whole.

This issue with "slow/unresponsive/not-working" comments should be a lot more specific and separated by Sublime Text version, and language. For that reason, I'm closing this issue not because it's fixed, but because I need more specifics, so please, please! **OPEN SEPARATED ISSUES** with this in mind and make sure the title is specific. i.e. "Sluggish ST2 when using PHP" or "Slow completion when using JavaScript in ST3". Make sure your comment includes all or the relevant bits (particularly tracebacks) in the console messages and codeintel.log **and** make sure you mention your platform and mention how many files you are using, if you use a project with many folders, and so on. If possible include examples/repos which I can use to reproduce the problem.

**Closed by Kronuz** 2015-01-22 14:43 UTC

**Comment by Kronuz** [comment] 2015-01-22 14:47
It is very likely some languages are the problem, as I've personally experienced sluggishness when using JavaScript (and HTML with JavaScript) some times.

**Comment by cvetan** [comment] 2015-01-24 00:17
But it works just fine on Windows. What could possibly kill it on Linux? Is it python, some of it's libraries? Personally i prefer ST2 ove ST3, but i have been using it only because of codeintel. On ST3 however some other plugins don't work.

**Comment by wizza-smile** [comment] 2015-01-24 05:06
Maybe it's something like this:
https://github.com/SublimeCodeIntel/SublimeCodeIntel/issues/388

**Comment by Kronuz** [comment] 2015-01-24 06:03
Yes, binaries have always been a problem (particularly, Linux binaries)

**Comment by ircsasw** [comment] 2015-01-24 06:26
In Windows also does not work with PHP in ST3.
My problem was solved by copying the folder ".codeintel" from ST2:
```
C:\Users\Arturo\AppData\Roaming\Sublime Text 2\Packages\SublimeCodeIntel
```
to ST3:
```
C:\Users\Arturo\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel
```
The ".codeintel" folder was not in the path ST3

Hope this helps.

**Comment by wizza-smile** [comment] 2015-01-24 07:08
https://github.com/SublimeCodeIntel/SublimeCodeIntel/issues/451
