### ISSUE TITLE
UnicodeEncodeError: 'gbk' codec can't encode character '\xcf' in position 20: illegal multibyte sequence

### ISSUE THREAD

**Issue by django-wong** [SublimeCodeIntel/SublimeCodeIntel#638] opened 2017-08-31 06:42 UTC
Hi @Kronuz 

Having this issue on:
Windows 10
Sublime Text 3 build 3142
Python36
pip 9.0.1
codeintel 2.0.0-beta.29
SublimeCodeIntel v3.0.0 beta27

```
Traceback (most recent call last):
  File "./python3.3/logging/__init__.py", line 941, in emit
UnicodeEncodeError: 'gbk' codec can't encode character '\xcf' in position 20: illegal multibyte sequence
Logged from file __init__.py, line 1794
```

```
Traceback (most recent call last):
  File "./python3.3/logging/__init__.py", line 941, in emit
UnicodeEncodeError: 'gbk' codec can't encode character '\xcf' in position 20: illegal multibyte sequence
Logged from file SublimeCodeIntel.py, line 508
Traceback (most recent call last):
  File "./python3.3/logging/__init__.py", line 941, in emit
UnicodeEncodeError: 'gbk' codec can't encode character '\xcf' in position 20: illegal multibyte sequence
Logged from file SublimeCodeIntel.py, line 528
```

**Comment by django-wong** [comment] 2017-08-31 07:15
The GBK issue is fixed by change computer language to English, but now I have this:
```
Exception in thread CodeIntel Manager Thread:
Traceback (most recent call last):
  File "C:\Users\Wilso\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\process.py", line 102, in <module>
    from subprocess import (SW_HIDE,
ImportError: cannot import name GetVersion

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "C:\Users\Wilso\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\codeintel.py", line 855, in run
    self.init_child()
  File "C:\Users\Wilso\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\codeintel.py", line 535, in init_child
    import process
  File "C:\Users\Wilso\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\libs\process.py", line 107, in <module>
    SW_HIDE = subprocess._subprocess.SW_HIDE
AttributeError: 'module' object has no attribute '_subprocess'
```

**Comment by Kronuz** [comment] 2017-08-31 13:39
The subprocess issue should be fixed in CodeIntel v2.0.0-beta.30 and SublimeCodeIntel v3.0.0-beta.28

Please reopen if the problem persists.

**Closed by Kronuz** 2017-08-31 13:39 UTC

**Comment by django-wong** [comment] 2017-09-01 17:27
Hi @Kronuz 

Tried CodeIntel v2.0.0-beta.30 and SublimeCodeIntel v3.0.0-beta.28 but still having the `_subprocess` issue so I made some changes to the source code and the `_subprocess` issue is gone but **getting new error**. The changes I have made could be wrong since I'm not familiar with Python. Just paste here and hope it helps.

```diff
 libs/process.py | 8 ++++----
 1 file changed, 4 insertions(+), 4 deletions(-)

diff --git a/libs/process.py b/libs/process.py
index 81f60b8..a334700 100644
--- a/libs/process.py
+++ b/libs/process.py
@@ -389,8 +389,8 @@ class ProcessOpen(Popen):
             if sys.platform != "win32":
                 cls.__needToHackAroundStdHandles = False
             else:
-                from _subprocess import GetStdHandle, STD_INPUT_HANDLE
-                stdin_handle = GetStdHandle(STD_INPUT_HANDLE)
+                from subprocess import STD_INPUT_HANDLE
+                stdin_handle = STD_INPUT_HANDLE
                 if stdin_handle is not None:
                     cls.__needToHackAroundStdHandles = True
                 else:
@@ -408,7 +408,7 @@ class ProcessOpen(Popen):
         @param fileobj The object being used as a fd/handle/whatever
         @param stream_name The name of the stream, "stdin", "stdout", or "stderr"
         """
-        import _subprocess
+        # import _subprocess
         import ctypes
         import msvcrt
         new_handle = None
@@ -427,7 +427,7 @@ class ProcessOpen(Popen):
                     "stdout": _subprocess.STD_OUTPUT_HANDLE,
                     "stderr": _subprocess.STD_ERROR_HANDLE,
                 }[stream_name]
-                handle = _subprocess.GetStdHandle(std_handle)
+                handle = std_handle
                 if handle is None:
                     # subprocess.Popen._get_handles creates a new pipe here
                     # we don't have to worry about things we create
```

This change will lead to an other error:
```
Error initing child: _execute_child() takes 17 positional arguments but 19 were given
```

If I remove the WindowsKillablePopen fix (/libs/process.py line 246), another error comes:
```
Error reading data from OOP CodeIntel: Type str doesn't support the buffer API
```

If I set `oop_mode` to `tcp`, then the status bar shows me that CodeIntel is ready and start to add some libraries (doesn't scan my source code) but when I type something, its just show me:
```
SublimeCodeIntel Notification Error: Unexpected error with evaluator  .... 
```

let me know if you need more infomation

**Comment by Kronuz** [comment] 2017-09-01 18:06
Released a new version of both (again) ...with some changes in `process.py`.

You can install the newest as it becomes available or replace `process.py` in `SublimeCodeIntel/libs/process.py` and `CodeIntel/codeintel/process.py` with this: https://github.com/Kronuz/CodeIntel/blob/a419b85fec7208bc0bd23690f0c8d6062a78ed90/codeintel/process.py

For the other error, I'd need to see the logs, because apparently it should be working.

**Comment by django-wong** [comment] 2017-09-01 18:09
Where I can find the log?

**Comment by django-wong** [comment] 2017-09-01 18:11
Just download and rename to .log
[codeintel.zip](https://github.com/SublimeCodeIntel/SublimeCodeIntel/files/1271121/codeintel.zip)

**Comment by Kronuz** [comment] 2017-09-01 23:43
@django-wong The log says the problem is in `_subprocess`, which should now be fixed. Please try upgrading CodeIntel and SublimeCodeIntel to the latest.

**Comment by django-wong** [comment] 2017-09-02 08:39
unlucky, still getting this issue:
```
Error initing child: _execute_child() takes 17 positional arguments but 19 were given
```

**Comment by Kronuz** [comment] 2017-09-03 19:10
Can you please try again with the latest versions. I removed special code about subprocesses I don't think it's necessary.

**Comment by django-wong** [comment] 2017-09-04 15:48
![screenshot 2017-09-04 23 45 18](https://user-images.githubusercontent.com/4019240/30033022-5734d31e-91cb-11e7-8348-1248234f7056.png)
It keeps open this window titled codeintel

**Comment by django-wong** [comment] 2017-09-04 15:50
Here is from console
```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 389, in run_callback
    expr()
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 458, in <lambda>
    run_callback('on_pre_save', callback, lambda: callback.on_pre_save(v))
  File "C:\Users\Wilso\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\SublimeCodeIntel.py", line 867, in on_pre_save
    buf = self.buf_from_view(view)
  File "C:\Users\Wilso\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\SublimeCodeIntel.py", line 526, in buf_from_view
    lang = self.guess_language(view, path)
  File "C:\Users\Wilso\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\SublimeCodeIntel.py", line 509, in guess_language
    if lang in settings.get('disabled_languages'):
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by Kronuz** [comment] 2017-09-04 16:20
The second problem should be fixed now... can you please try upgrading everything again?
