### ISSUE TITLE
Default ST autocomplete not working

### ISSUE THREAD

**Issue by alex-coder** [SublimeCodeIntel/SublimeCodeIntel#459] opened 2015-01-16 11:16 UTC
Hello!

I'm just install ST3 and **SublimeCodeIntel** from PackageControl.
And i have no longer see the default ST completions.
Alt+/ or ctrl+space *not working*.

Ubuntu 14.04

**Comment by DavidPD** [comment] 2015-01-16 14:42
I'm having the same issue. I haven't found any workaround other than uninstalling CodeIntel, simply disabling via `Package Control: Disable Package` doesn't work.

I've tried messing with `codeintel_word_completions`, `codeintel_live`, `codeintel_enabled_languages` and `sublime_auto_complete` which no longer seems to exist.

I'm using ST3 on a Mac with Mavericks v10.9.5

**Comment by Kronuz** [comment] 2015-01-16 14:56
I believe this issue will be fixed in the next release, later today.

**Comment by matheusrocha89** [comment] 2015-01-17 21:08
I am having the same problem, trying to find how to fix it.

**Comment by Marrin** [comment] 2015-01-18 12:59
Same problem here, with ST2, and still after the SublimeCodeIntel 2.1.2 update from 2015-01-16.

**Comment by matheusrocha89** [comment] 2015-01-18 13:27
@Marrin me too, didn't found a solution, the only solution was to remove the SublimeCodeIntel plugin, even disabling is not solving.

**Comment by Kronuz** [comment] 2015-01-18 13:52
Please close Sublime Text, delete your ~/.codeintel and start it again; then try doing some things with the files in your project. Remember that the database is being regenerated with this procedure, so you'll see it takes some time to autocomplete the first few times, you'll have to wait a bit for things to be fast again. If you still can't use it, make sure Sblime Text didn't add SublimeCodeIntel to the list of ignored packages (it happens some times when plugins are being installed/upgraded. Select the Preferences/Settings - Default menu item, and remove SublimeCodeIntel from `ignored_packages`). If the problem persists, please provide messages from the Sublime Text console and from `~/.codeintel/codeintel.log`

**Comment by matheusrocha89** [comment] 2015-01-18 14:11
@Kronuz this folder does not exist in my mac, can't find `~/.codeintel`

**Comment by Marrin** [comment] 2015-01-18 22:53
@Kronuz No change.  Just to be clear the SublimeCodeIntel completion works it's ”magic”, i.e. I get completion for Python variables and attributes on objects, but no suggestions from the text of the files.  Which is especially bad in actual text files and languages not supported by SublimeCodeIntel because there I get no completion _at all_, unless I completely deinstall the SublimeCodeIntel plugin. Just disabling it won't do.

The following is from opening ST and editing as Python file and a plain text file and a reStructuredText file.  Only the Python file editing produced some text in the log file:

`~/codeintel/codeintel.log`:

```
Starting logging SublimeCodeIntel v2.1.1 rev GIT-unknown (1421619448) on Sun Jan 18 23:33:30 2015
=================================================================================================
Updating indexes for 'Python'... The first time this can take a while.
Doing CodeIntel for 'Python' (hold on)...
Done 'Python' CodeIntel! Full CodeIntel took 151ms
Doing CodeIntel for 'Python' (hold on)...
Done 'Python' CodeIntel! Full CodeIntel took 8ms
Updating indexes for 'Python'... The first time this can take a while.
Doing CodeIntel for 'Python' (hold on)...
Done 'Python' CodeIntel! Full CodeIntel took 17ms
Updating indexes for 'Python'... The first time this can take a while.
Doing CodeIntel for 'Python' (hold on)...
eval 'fibonacci_sequence' at forum5.py#41  <Trigger 'python-complete-object-members' at 891 (explicit)>
start scope is (<blob 'forum5'>, ['main'])
find 'fibonacci_sequence ...' starting at (<blob 'forum5'>, ['main']):
is 'fibonacci_sequence' accessible on (<blob 'forum5'>, ['main'])? yes: <variable 'fibonacci_sequence'>
resolve 'FibonacciIterator' type inference for <variable 'fibonacci_sequence'>:
find 'FibonacciIterator ...' starting at (<blob 'forum5'>, ['main']):
File u'/home/bj/get-pip.py' has size greater than 1MB (1340903)
+ Info: Doing CodeIntel for 'Python' (hold on)...
File '/home/bj/get-pip.py' has size greater than 1MB (1340903)
+ Event: Adding python-2.7 stdlib
done eval: timed out
Done 'Python' CodeIntel! Full CodeIntel took ~20s
+ Info: Timeout while resolving completions!
is 'FibonacciIterator' accessible on (<blob 'forum5'>, ['main'])? no
is 'FibonacciIterator' accessible on (<blob 'forum5'>, [])? yes: <class 'FibonacciIterator'>
'FibonacciIterator' is <class 'FibonacciIterator'> on (<blob 'forum5'>, [])
'fibonacci_sequence' is <class 'FibonacciIterator'> on (<blob 'forum5'>, [])
resolve 'object' type inference:
find 'object ...' starting at (<blob 'forum5'>, []):
is 'object' accessible on (<blob 'forum5'>, [])? no
is 'object' accessible on (<blob '*'>, [])? yes: <class 'object'>
'object' is <class 'object'> on (<blob '*'>, [])
    cplns: [('variable', 'a'), ('variable', 'b'), ('function', 'next'), ('function', 'previous'), ('variable', '__class__'), ('function', '__delattr__'), ('variable', '__doc__'), ('function', '__format__'), ('function', '__getattribute__'), ('function', '__hash__'), ('function', '__init__'), ('function', '__int__'), ('function', '__reduce_ex__'), ('function', '__reduce__'), ('function', '__repr__'), ('function', '__setattr__'), ('function', '__sizeof__'), ('function', '__str__')]
done eval: success
Updating indexes for 'Python'... The first time this can take a while.
Doing CodeIntel for 'Python' (hold on)...
eval 'fibonacci_sequence' at forum5.py#41  <Trigger 'python-complete-object-members' at 891 (explicit)>
start scope is (<blob 'forum5'>, ['main'])
find 'fibonacci_sequence ...' starting at (<blob 'forum5'>, ['main']):
is 'fibonacci_sequence' accessible on (<blob 'forum5'>, ['main'])? yes: <variable 'fibonacci_sequence'>
resolve 'FibonacciIterator' type inference for <variable 'fibonacci_sequence'>:
find 'FibonacciIterator ...' starting at (<blob 'forum5'>, ['main']):
is 'FibonacciIterator' accessible on (<blob 'forum5'>, ['main'])? no
is 'FibonacciIterator' accessible on (<blob 'forum5'>, [])? yes: <class 'FibonacciIterator'>
'FibonacciIterator' is <class 'FibonacciIterator'> on (<blob 'forum5'>, [])
'fibonacci_sequence' is <class 'FibonacciIterator'> on (<blob 'forum5'>, [])
resolve 'object' type inference:
find 'object ...' starting at (<blob 'forum5'>, []):
is 'object' accessible on (<blob 'forum5'>, [])? no
is 'object' accessible on (<blob '*'>, [])? yes: <class 'object'>
'object' is <class 'object'> on (<blob '*'>, [])
    cplns: [('variable', 'a'), ('variable', 'b'), ('function', 'next'), ('function', 'previous'), ('variable', '__class__'), ('function', '__delattr__'), ('variable', '__doc__'), ('function', '__format__'), ('function', '__getattribute__'), ('function', '__hash__'), ('function', '__init__'), ('function', '__int__'), ('function', '__reduce_ex__'), ('function', '__reduce__'), ('function', '__repr__'), ('function', '__setattr__'), ('function', '__sizeof__'), ('function', '__str__')]
done eval: success
Done 'Python' CodeIntel! Full CodeIntel took 11ms
Autocomplete called (Python) [cplns]
```

ST console ouput:

```
startup, version: 2221 linux x32 channel: stable
executable: /home/bj/src/Sublime Text 2/sublime_text
working dir: /home/bj
packages path: /home/bj/.config/sublime-text-2/Packages
settings path: /home/bj/.config/sublime-text-2/Settings
PackageSetup not required
Py_GetProgramName(): sublime_text
Py_GetExecPrefix(): .
Py_GetProgramFullPath(): /usr/bin/sublime_text
Py_GetPath(): ./lib/python26.zip:./lib/python2.6/:./lib/python2.6/plat-linux2:./lib/python2.6/lib-tk:./lib/python2.6/lib-old:./lib/python2.6/lib-dynload
Py_GetPythonHome(): .
catalogue loaded
found 29 files for base name Default.sublime-keymap
found 2 files for base name Default.sublime-mousemap
found 24 files for base name Main.sublime-menu
Reloading plugin /home/bj/.config/sublime-text-2/Packages/0_package_control_loader/00-package_control.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/0_package_control_loader/01-ssl-linux.py
Linux SSL: successfully loaded _ssl module for libssl.so.1.0.0
Reloading plugin /home/bj/.config/sublime-text-2/Packages/0_package_control_loader/02-bz2.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/AutoPEP8/sublautopep8.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/CSS/css_completions.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/ChangeQuotes/change_quotes.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/CoffeeScript/CoffeeScript.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Comments Aware Enter/comments_aware_enter.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Crypto/Crypto.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Default/comment.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Default/copy_path.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Default/delete_word.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Default/detect_indentation.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Default/duplicate_line.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Default/echo.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Default/exec.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Default/fold.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Default/font.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Default/goto_line.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Default/indentation.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Default/kill_ring.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Default/mark.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Default/new_templates.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Default/open_file_settings.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Default/open_in_browser.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Default/paragraph.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Default/save_on_focus_lost.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Default/scroll.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Default/set_unsaved_view_name.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Default/side_bar.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Default/sort.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Default/swap_line.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Default/switch_file.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Default/transform.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Default/transpose.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Default/trim_trailing_white_space.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Diff/diff.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Django-Tools/django_comment.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Emmet/emmet-plugin.py
Emmet: No need to update PyV8
Reloading plugin /home/bj/.config/sublime-text-2/Packages/External Command/external_command.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Fabric Tasks/Sublime-Fabric.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Fabric Tasks/fabprocess.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Fabric Tasks/fabric_wrapper.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Figlet Big ASCII Text/figlet.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/FindKeyConflicts/find_key_conflicts.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Format SQL/FormatSQL.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/HTML/encode_html_entities.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/HTML/html_completions.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/LaTeXTools/delete_temp_files.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/LaTeXTools/getTeXRoot.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/LaTeXTools/jumpToPDF.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/LaTeXTools/latexCommand.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/LaTeXTools/latexEnvCloser.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/LaTeXTools/latexEnvironment.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/LaTeXTools/latex_cite_completions.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/LaTeXTools/latex_ref_cite_completions.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/LaTeXTools/latex_ref_completions.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/LaTeXTools/makePDF.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/LaTeXTools/migrate.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/LaTeXTools/parseTeXlog.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/LaTeXTools/texMacro.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/LaTeXTools/texSections.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/LaTeXTools/toggle_auto.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/LaTeXTools/toggle_focus.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/LaTeXTools/toggle_fwdsync.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/LaTeXTools/toggle_show.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/LaTeXTools/viewPDF.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Markboard/Markboard.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Markboard/MarkboardClippers.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Markboard/markdown2.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Markboard/winClip.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./winClip.py", line 9, in <module>
    import win32clipboard
ImportError: No module named win32clipboard
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Mediawiker/mediawiker.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Mediawiker/mwsetup.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Mediawiker/mwutils.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Nodejs/Nodejs.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Nodejs/__init__.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Package Control/Package Control.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Package Control/bootstrap.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Pandoc (Markdown)/PandocRender.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/PlainTasks/PlainTasks.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/PowerShell/setup.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./setup.py", line 11, in <module>
    from distutils import log, dir_util, dep_util, file_util, archive_util
ImportError: No module named distutils
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Print to HTML/PrintToHTML.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Pylinter/multiconf.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Pylinter/pylinter.py
 - PyLinter: Pylint executable found
 - PyLinter: Pylint version (1, 4, 1) found
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Python Imports Sorter/__init__.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Python Imports Sorter/organizer.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Python Imports Sorter/python_imports_sorter.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Restructured Text (RST) Snippets/footnotes.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Restructured Text (RST) Snippets/headers.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Restructured Text (RST) Snippets/helpers.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Restructured Text (RST) Snippets/indent_list_item.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Restructured Text (RST) Snippets/lists.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Restructured Text (RST) Snippets/render.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Restructured Text (RST) Snippets/simpleformat.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Restructured Text (RST) Snippets/tables.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/RestructuredText Improved/RestructuredText Improved.py
user_preferences_file: /home/bj/.config/sublime-text-2/Packages/User/Preferences.sublime-settings
s: {
  "auto_complete_selector": "source, text",
  "color_scheme": "Packages/Color Scheme - Default/Solarized (Dark).tmTheme",
  "dictionary": "Packages/Language - English/en_GB.dic",
  "figlet_font": "rounded",
  "font_face": "Fixedsys Excelsior 3.01-L",
  "font_size": 12.0,
  "highlight_line": true,
  "highlight_modified_tabs": true,
  "ignored_packages":
  [
    "Vintage",
    "Jedi - Python autocompletion",
    "AAAPackageDev",
    "SublimeRope",
    "RestructuredText"
  ],
  "indent_guide_options":
  [
    "draw_normal",
    "draw_active"
  ],
  "rulers":
  [
    80,
    120
  ],
  "shift_tab_unindent": true,
  "translate_tabs_to_spaces": true,
  "word_wrap": true
}

Reloading plugin /home/bj/.config/sublime-text-2/Packages/ScopeHunter/scope_hunter.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/SetDjangoSyntax/SetDjangoSyntax.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/SideBarEnhancements/SideBar.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/SideBarEnhancements/StatusBarFileSize.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/SideBarEnhancements/StatusBarModifiedTime.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/SublimeCodeIntel/SublimeCodeIntel.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/SublimeCodeIntel/ordereddict.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Table Cleaner/table_cleaner.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Table Cleaner/table_commons.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Table Cleaner/table_import.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Table Editor/table_base.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Table Editor/table_border_syntax.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Table Editor/table_emacs_org_mode_syntax.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Table Editor/table_lib.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Table Editor/table_lib_test.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Table Editor/table_line_parser.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Table Editor/table_multi_markdown_syntax.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Table Editor/table_pandoc_syntax.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Table Editor/table_plugin.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Table Editor/table_plugin_test.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Table Editor/table_re_structured_text_syntax.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Table Editor/table_simple_syntax.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Table Editor/table_textile_syntax.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Table Editor/widechar_support.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/Taskwarrior/sublime-taskwarrior.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/TodoReview/TodoReview.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./TodoReview.py", line 10, in <module>
    import io
  File ".\io.py", line 63, in <module>
ImportError: No module named _fileio
Reloading plugin /home/bj/.config/sublime-text-2/Packages/User/something.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/YAML Nav/utils.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/YAML Nav/view_data.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/YAML Nav/worker.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/YAML Nav/yaml_math.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/YAML Nav/yaml_nav.py
Reloading plugin /home/bj/.config/sublime-text-2/Packages/requirementstxt/requirements.py
plugin init time: 0.72478
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
pre session restore time: 0.817158
using gamma: 1 (err: 0)
wrote startup cache, added files: 6 orphaned files: 0 total files: 184 cache hits: 178
startup time: 1.11041 (package setup was not run)
Not python file - SetDjangoSyntax exiting
Not python file - SetDjangoSyntax exiting
Not python file - SetDjangoSyntax exiting
Not python file - SetDjangoSyntax exiting
Not python file - SetDjangoSyntax exiting
Not python file - SetDjangoSyntax exiting
Not python file - SetDjangoSyntax exiting
Not python file - SetDjangoSyntax exiting
loaded 1124 snippets
Package Control: Skipping automatic upgrade, last run at 2015-01-18 23:13:21, next run at 2015-01-19 00:13:21 or after
+ Info: processing `Python': please wait...
processing `Python': please wait...
[FindKeyConflicts] WARNING Could not import subprocess32 module, falling back to subprocess module
[FindKeyConflicts] INFO db upgrade is necessary
[FindKeyConflicts] INFO eval 'fibonacci_sequence' at forum5.py#41  <Trigger 'python-complete-object-members' at 891 (explicit)>
[FindKeyConflicts] INFO start scope is (<blob 'forum5'>, ['main'])
[FindKeyConflicts] INFO find 'fibonacci_sequence ...' starting at (<blob 'forum5'>, ['main']):
[FindKeyConflicts] INFO is 'fibonacci_sequence' accessible on (<blob 'forum5'>, ['main'])? yes: <variable 'fibonacci_sequence'>
[FindKeyConflicts] INFO resolve 'FibonacciIterator' type inference for <variable 'fibonacci_sequence'>:
[FindKeyConflicts] INFO find 'FibonacciIterator ...' starting at (<blob 'forum5'>, ['main']):
[FindKeyConflicts] WARNING File u'/home/bj/get-pip.py' has size greater than 1MB (1340903)
Doing CodeIntel for 'Python' (hold on)...
[FindKeyConflicts] WARNING File '/home/bj/get-pip.py' has size greater than 1MB (1340903)
Adding python-2.7 stdlib
[FindKeyConflicts] INFO done eval: timed out
Timeout while resolving completions!
current triggername: 'python-complete-object-members'
[FindKeyConflicts] INFO is 'FibonacciIterator' accessible on (<blob 'forum5'>, ['main'])? no
[FindKeyConflicts] INFO is 'FibonacciIterator' accessible on (<blob 'forum5'>, [])? yes: <class 'FibonacciIterator'>
[FindKeyConflicts] INFO 'FibonacciIterator' is <class 'FibonacciIterator'> on (<blob 'forum5'>, [])
[FindKeyConflicts] INFO 'fibonacci_sequence' is <class 'FibonacciIterator'> on (<blob 'forum5'>, [])
[FindKeyConflicts] INFO resolve 'object' type inference:
[FindKeyConflicts] INFO find 'object ...' starting at (<blob 'forum5'>, []):
[FindKeyConflicts] INFO is 'object' accessible on (<blob 'forum5'>, [])? no
[FindKeyConflicts] INFO is 'object' accessible on (<blob '*'>, [])? yes: <class 'object'>
[FindKeyConflicts] INFO 'object' is <class 'object'> on (<blob '*'>, [])
[FindKeyConflicts] INFO     cplns: [('variable', 'a'), ('variable', 'b'), ('function', 'next'), ('function', 'previous'), ('variable', '__class__'), ('function', '__delattr__'), ('variable', '__doc__'), ('function', '__format__'), ('function', '__getattribute__'), ('function', '__hash__'), ('function', '__init__'), ('function', '__int__'), ('function', '__reduce_ex__'), ('function', '__reduce__'), ('function', '__repr__'), ('function', '__setattr__'), ('function', '__sizeof__'), ('function', '__str__')]
[FindKeyConflicts] INFO done eval: success
[FindKeyConflicts] INFO eval 'fibonacci_sequence' at forum5.py#41  <Trigger 'python-complete-object-members' at 891 (explicit)>
[FindKeyConflicts] INFO start scope is (<blob 'forum5'>, ['main'])
[FindKeyConflicts] INFO find 'fibonacci_sequence ...' starting at (<blob 'forum5'>, ['main']):
[FindKeyConflicts] INFO is 'fibonacci_sequence' accessible on (<blob 'forum5'>, ['main'])? yes: <variable 'fibonacci_sequence'>
[FindKeyConflicts] INFO resolve 'FibonacciIterator' type inference for <variable 'fibonacci_sequence'>:
[FindKeyConflicts] INFO find 'FibonacciIterator ...' starting at (<blob 'forum5'>, ['main']):
[FindKeyConflicts] INFO is 'FibonacciIterator' accessible on (<blob 'forum5'>, ['main'])? no
[FindKeyConflicts] INFO is 'FibonacciIterator' accessible on (<blob 'forum5'>, [])? yes: <class 'FibonacciIterator'>
[FindKeyConflicts] INFO 'FibonacciIterator' is <class 'FibonacciIterator'> on (<blob 'forum5'>, [])
[FindKeyConflicts] INFO 'fibonacci_sequence' is <class 'FibonacciIterator'> on (<blob 'forum5'>, [])
[FindKeyConflicts] INFO resolve 'object' type inference:
[FindKeyConflicts] INFO find 'object ...' starting at (<blob 'forum5'>, []):
[FindKeyConflicts] INFO is 'object' accessible on (<blob 'forum5'>, [])? no
[FindKeyConflicts] INFO is 'object' accessible on (<blob '*'>, [])? yes: <class 'object'>
[FindKeyConflicts] INFO 'object' is <class 'object'> on (<blob '*'>, [])
[FindKeyConflicts] INFO     cplns: [('variable', 'a'), ('variable', 'b'), ('function', 'next'), ('function', 'previous'), ('variable', '__class__'), ('function', '__delattr__'), ('variable', '__doc__'), ('function', '__format__'), ('function', '__getattribute__'), ('function', '__hash__'), ('function', '__init__'), ('function', '__int__'), ('function', '__reduce_ex__'), ('function', '__reduce__'), ('function', '__repr__'), ('function', '__setattr__'), ('function', '__sizeof__'), ('function', '__str__')]
[FindKeyConflicts] INFO done eval: success
[FindKeyConflicts] INFO Autocomplete called (Python) [cplns]
current triggername: 'python-complete-object-members'
```

**Comment by alex-coder** [comment] 2015-01-19 12:27
Last update resolved my problem (PHP). But I really want to see suggestions instantly, not after 1-2 seconds )

**Comment by alex-coder** [comment] 2015-01-19 12:59
Last update solved partially my problem. If I start write in a new line suggestions will be shown, but if I write in position like 
```php
$this->assertTrue(in_[here])
```
ST don't show me suggestion like `in_array`, etc.

**Comment by Zeeker** [comment] 2015-01-19 13:07
I can confirm. Noticed this while trying to use [Plain Tasks](https://github.com/aziz/PlainTasks) completions in my TODO file. I wasn't able to use any completions offered by Plain Tasks.

Disabling SublimeCodeIntel solved the issue.

**Comment by wizza-smile** [comment] 2015-01-19 13:11
Sublimes default completions have been fixed in **SublimeCodeIntel3**!
now, if you remove a language from "codeintel_enabled_langugages", it will trigger sublime completions as if SublimeCodeIntel was not installed.

**Comment by alex-coder** [comment] 2015-01-19 13:17
@wizza-smile, but if I will enables some language, it will not work?

**Comment by Zeeker** [comment] 2015-01-19 13:23
@wizza-smile As you can imagine the [Plain Tasks](https://github.com/aziz/PlainTasks) syntax/language isn't listed in `codeintel_enabled_languages`. Nevertheless SublimeCodeIntel seemed to mess with the autocompletion offered by this plugin in such files.

I am just reporting what I'm experiencing.

**Comment by wizza-smile** [comment] 2015-01-19 13:36
@Zeeker sorry, I can only give explicit support for SublimeCodeIntel3 users! Find it here:
https://github.com/wizza-smile/SublimeCodeIntel3

**Comment by wizza-smile** [comment] 2015-01-19 22:53
Hi @alex-coder,  
I just implemented 
´´´
$this->assertTrue(in_[here])
´´´
in **SublimeCodeIntel3**! 
It would be da bomb and extremly helpful, if you could check that out and give me feedback (or more feature requests).
Sublime's default completions (for example in plain text or foreign Syntaxes like "Plain Tasks" have also been fixed!

Let me hear from ya!

**Comment by alex-coder** [comment] 2015-01-20 09:17
@wizza-smile, it seems to works. Thanks a lot!

**Comment by ptcong** [comment] 2015-01-20 11:03
@wizza-smile i just try to download SublimeCodeIntel3 and put to Packges/ but when i go to settings, it open SublimeCodeIntel settings. I renamed it to SublimeCodeIntel, but same result.

**Comment by Kronuz** [comment] 2015-01-22 15:03
Default ST autocomplete should be working in more recent versions of SublimeCodeIntel, thanks to pulled code from wizza-smile's fork.

**Closed by Kronuz** 2015-01-22 15:03 UTC

**Comment by juliolopez78** [comment] 2015-04-07 11:05
For what it's worth, I had the same issue just yesterday and after much digging around in pref files, resetting Sublime back to defaults and re-installing all my pkgs, I discovered that my project's workspace file was the culprit. I simply deleted the sublime-workspace file, restarted Sublime and was good to go.

**Comment by suntwin** [comment] 2016-02-23 20:58
Hi

Is this still an issue. I have tried real hard to enable ST3 autocomplete with nodejs. However I have been unable to achieve any success.
It always fail to identify the nodejs variables as shown in the codeIntel.log

`Done 'JavaScript' CodeIntel! Full CodeIntel took 6ms
Autocomplete called (JavaScript) [cplns]
Doing CodeIntel for 'JavaScript' (hold on)...
Done 'JavaScript' CodeIntel! Full CodeIntel took 1ms
Doing CodeIntel for 'JavaScript' (hold on)...
Done 'JavaScript' CodeIntel! Full CodeIntel took 1ms
Doing CodeIntel for 'JavaScript' (hold on)...
Done 'JavaScript' CodeIntel! Full CodeIntel took 1ms
Doing CodeIntel for 'JavaScript' (hold on)...
eval 'serv1' at Block_Event.js#3  <Trigger 'javascript-complete-object-members' at 51>
start scope is (<Element 'scope' at 0x0000000006138518>, [])
find 'serv1' starting at (<Element 'scope' at 0x0000000006138518>, [])
is 'serv1' accessible on (<Element 'scope' at 0x0000000006138518>, [])? yes
_hit_from_first_part: found elem: variable 'serv1' at []
lookup 'serv1' in <JavaScript extradirslib>
lookup 'serv1' in <JavaScript cataloglib: >
lookup 'serv1' in <javascript stdlib>
resolve 'require()' type inference for <Element 'variable' at 0x0000000006138DD8>:
find 'require' starting at (<Element 'scope' at 0x0000000006138518>, [])
is 'require' accessible on (<Element 'scope' at 0x0000000006138518>, [])? no
is 'require' accessible on (<Element 'scope' at 0x0000000006138C18>, [])? yes
_hit_from_first_part: found elem: function 'require' at []
lookup 'require' in <JavaScript extradirslib>
lookup 'require' in <JavaScript cataloglib: >
lookup 'require' in <javascript stdlib>
found 1 hits in lib
_hits_from_call: no resolver on <Element 'scope' at 0x00000000061384A8>
could resolve call on <Element 'scope' at 0x00000000061384A8>: no return type info for <Element 'scope' at 0x00000000061384A8>
_hits_from_call: no resolver on <Element 'scope' at 0x00000000061384A8>
could resolve call on <Element 'scope' at 0x00000000061384A8>: no return type info for <Element 'scope' at 0x00000000061384A8>
evaluating 'serv1' at Block_Event.js#3: No completions found
done eval: eval error
Done 'JavaScript' CodeIntel! Full CodeIntel took 11ms
+ Warning: evaluating 'serv1' at Block_Event.js#3: No completions found`

Here is the screenshot from editor
![untitled](https://cloud.githubusercontent.com/assets/9293282/13266417/21039a8a-dacc-11e5-8aa7-62a190936446.png)
![untitled](https://cloud.githubusercontent.com/assets/9293282/13266450/450352b8-dacc-11e5-894c-43d86d67f5b6.png)
