### ISSUE TITLE
You released the wrong version!

### ISSUE THREAD

**Issue by wizza-smile** [SublimeCodeIntel/SublimeCodeIntel#453] opened 2015-01-14 00:16 UTC
@Kronuz Dude, you merged an incomplete state of my fork. There are some bugs in there, that I already fixed!
Also: You should mention my project's name in the "What's New", since that is where your code is coming from and that is the way I decided to play it for now. The way you're currently doing it is turning me off, nuff said.

It's called SublimeCodeIntel3, thank you! 

The final code can be found here:
https://github.com/wizza-smile/SublimeCodeIntel3

**Comment by dschu-lab** [comment] 2015-01-14 08:36
After updating (Just started ST2) my CodeIntel doesn't work anymore. Does it have something to do with the wrong merge? It is pretty frustrating, I guess I should disable AutoUpdate..

There is no .codeintel folder generated in '~/' and I don't see any log. Don't know how to troubleshoot this..

**Comment by minitauros** [comment] 2015-01-14 09:10
When I press ctrl+shift+space to trigger codeIntel autocompletion (for a PHP native function: is_a()), the codeIntel pops up, but when I press [enter], the arguments aren't written to my document so that I can easily write them. Before, this did work. Just reporting this so that it can be fixed :).

**Comment by dschu-lab** [comment] 2015-01-14 09:16
In @wizza-smile fork is an information in the changelog: 'only working with ST3'
Guess that's why it's called SublimeCodeIntel3 + Why it's not working with my ST2.. 

This is not the way it should go, isn't it? Why do you guys updating code that can't run in ST2?

There should be 2 repos for each ST2 and ST3 to support both versions, because ST3 is still in beta.
Or one repo which supports both, but you can't replace a ST2 Repo with a ST3-only repo..

**Comment by wizza-smile** [comment] 2015-01-14 09:29
@dschu-lab sorry to hear that! If you depend on autocomplete you should probably switch back to 2.0.6, follow the instructions in this s.o.:
http://stackoverflow.com/questions/7832770/get-certain-commit-from-github-project

**Comment by wizza-smile** [comment] 2015-01-14 09:31
thanx @minitauros, confirmed, I'll fix that asap!

**Comment by kch42** [comment] 2015-01-14 09:50
I also still use ST2, here's what I've done to downgrade to 2.0.6, which works well with ST2:

1. Tell Package Control to not upgrade SublimeCodeIntel. To do this, place this into `Packages/User/Package Control.sublime-settings`:
  
        "auto_upgrade_ignore": [
            "SublimeCodeIntel"
        ]

2. Download Version 2.0.6: https://github.com/SublimeCodeIntel/SublimeCodeIntel/releases/tag/v2.0.6 and place it into `Packages/SublimeCodeIntel`, replacing the new version.
3. Close Sublime Text
4. (I'm not sure, if this step is actually needed) Delete Codeintels cache (See https://github.com/SublimeCodeIntel/SublimeCodeIntel#troubleshooting)
5. Restart Sublime Text

HTH

**Comment by dschu-lab** [comment] 2015-01-14 09:56
@kch42 Thanks, your first point was exactly what I was looking for! :+1:

**Comment by kch42** [comment] 2015-01-14 10:11
@dschu-lab Glad I could help :)

**Comment by minitauros** [comment] 2015-01-14 10:31
@wizza-smile Don't know what I did exactly, but after a couple of sublime restarts and project switches (not to try and fix the problem, but just for project work) the problem I mentioned before does not seem to occur any more.

**Comment by wizza-smile** [comment] 2015-01-14 11:07
@minitauros exactly!

**Comment by matiasvad** [comment] 2015-01-14 15:41
I can confirm that this release does not work properly in ST3 either. Downgrading now.

**Comment by Kronuz** [comment] 2015-01-14 18:52
Granted, I rushed and released v2.1.0 hastily and somehow recklessly, but for a reason: I wanted to stir the community a little so everyone realizes: **HELP IS NEEDED**.

Instead of dividing the efforts or not merging in all wizza-smile great changes as soon as possible (because they were too many and I couldn't just "merge" because the pull request was on the release repository, or whatever) I decided to go ahead and undertake the hard task of cherry-pick each single commit in his pull request and merge as much as possible from his fork to the proper repositories. The reason is I wanted to merge as much as possible from wizza-smile's repo *BEFORE* updating the Komodo baseline. The idea is to have FULLY FUNCTIONAL version of SublimeCodeIntel before going into upgrading the codeintel2 engine from Komodo's source code, which is something I'm planning to do soon.

I now have merged in all the remaining changes in his fork and also I've released v2.1.1 which I verified that it now works in Sublime Text 2.

Please if you can help or have feedback, I'll hang around at irc://irc.freenode.net/#sublimecodeintel

**Comment by wizza-smile** [comment] 2015-01-14 19:05
:clap:

**Comment by b9sk** [comment] 2015-01-15 07:09
yep. 2.1.1 is broken on ST2. Jump To Symbol Defenition not workig yet after today update. 2.0.6 work fine even you copypast it from win to linux.

**Comment by ptcong** [comment] 2015-01-15 07:48
one more thing, the new version overrides PHP Completions Kit  (PCK) function arguments suggestion.
Eg: when i type `substr` and choose *standard function* of PCK suggestion, it give me

 `substr(string[, start, length)` then i will easy to fill how many arguments  i want by TAB -> fill.

Now with the version it only give me `substr()`. 

Is there anyway/setting to tell SublimeCodeIntel give me arguments hint ?

**Comment by matiasvad** [comment] 2015-01-15 14:13
At 2.1.1 ST3 is working for me again. Thanks.

**Comment by minitauros** [comment] 2015-01-16 08:07
Hm I don't know if it has anything to do with the update, but I can't seem to disable the "live" option of code intel. Even though I have it set to false, the code intel popup pops up as soon as I start typing anything that can be code intell-ed (I usually only want it to pop up when I press ctrl + shift + space).

**Closed** 2015-01-16 09:12 UTC
