### ISSUE TITLE
Completely hangs out ST3

### ISSUE THREAD

**Issue by masscrx** [SublimeCodeIntel/SublimeCodeIntel#447] opened 2014-12-28 13:30 UTC
After installing SublimeCodeIntel, I've met problem with autocompletion (plugin hangs out application) but now when I'm trying to remove package or disable, the same problem occurs, so it completely broke application. Windows 8, ST3 3065

**Comment by douglascamata** [comment] 2015-01-08 20:27
Same issue here.

**Comment by LOQUILLO** [comment] 2015-01-21 15:02
Same issue here.
Windows 7 x64
ST 3 build 3066

**Comment by wizza-smile** [comment] 2015-01-21 16:16
If any of you would be willing to try [**SublimeCodeIntel3**](https://github.com/wizza-smile/SublimeCodeIntel3) , that would be so helpful.
There is a good chance your problem is not present in that fork of this project.
Please provide feedback!

all the best

**Comment by Kronuz** [comment] 2015-01-22 15:19
It is very likely some languages are the problem, as I've personally experienced sluggishness only when using JavaScript (and HTML with JavaScript) some times.

This issue should be a lot more specific and separated by Sublime Text version, and language. For that reason, I'm closing this issue not because it's fixed, but because I need more specifics, so please, please! **OPEN SEPARATED ISSUES** with this in mind and make sure the title is specific. i.e. "Sluggish ST2 when using PHP" or "Slow completion when using JavaScript in ST3". Make sure your comment includes all or the relevant bits (particularly tracebacks) in the console messages and codeintel.log **and** make sure you mention your platform and mention how many files you are using, if you use a project with many folders, and so on. If possible include examples/repos which I can use to reproduce the problem.

Same as #286

**Closed by Kronuz** 2015-01-22 15:19 UTC
